// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/api-hub" | "/assistant" | "/contract" | "/dashboard" | "/feasibility" | "/jeonse" | "/jeonse/analysis" | "/jeonse/fixed-date" | "/jeonse/jeonse-right" | "/jeonse/lease-registration" | "/jeonse/lease-report" | "/jeonse/transfer" | "/legal" | "/login" | "/prediction" | "/pricing" | "/privacy" | "/profile" | "/registry" | "/report" | "/rights" | "/signup" | "/tax" | "/terms" | "/verification"
type AppRouteHandlerRoutes = "/api/admin/account" | "/api/admin/analyses" | "/api/admin/announcements" | "/api/admin/announcements/[id]" | "/api/admin/audit-logs" | "/api/admin/settings" | "/api/admin/stats" | "/api/admin/training-data" | "/api/admin/training-data/[id]" | "/api/admin/training-data/bulk-approve" | "/api/admin/training-data/export" | "/api/admin/users" | "/api/admin/users/[id]" | "/api/admin/verify" | "/api/admin/vocabulary" | "/api/admin/vocabulary/[id]" | "/api/admin/vocabulary/export" | "/api/admin/vocabulary/seed" | "/api/analyze-contract" | "/api/analyze-rights" | "/api/analyze-unified" | "/api/auth/[...nextauth]" | "/api/chat" | "/api/credit-check" | "/api/cron/fraud-import" | "/api/cron/registry-monitor" | "/api/extract-pdf" | "/api/feasibility/parse" | "/api/feasibility/report" | "/api/feasibility/verify" | "/api/fraud-cases" | "/api/fraud-risk" | "/api/generate-document" | "/api/monitoring" | "/api/monitoring/alerts" | "/api/monitoring/alerts/[id]" | "/api/parse-registry" | "/api/predict-value" | "/api/predict-value/compare" | "/api/real-price" | "/api/scholar/search" | "/api/stt/transcribe" | "/api/subscription" | "/api/subscription/cancel" | "/api/user/migrate-data" | "/api/user/notifications" | "/api/user/profile" | "/api/user/setup-role" | "/api/user/usage" | "/api/verification/request" | "/api/verification/respond" | "/api/verification/shared" | "/api/verification/shared/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/jeonse"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api-hub": {}
  "/api/admin/account": {}
  "/api/admin/analyses": {}
  "/api/admin/announcements": {}
  "/api/admin/announcements/[id]": { "id": string; }
  "/api/admin/audit-logs": {}
  "/api/admin/settings": {}
  "/api/admin/stats": {}
  "/api/admin/training-data": {}
  "/api/admin/training-data/[id]": { "id": string; }
  "/api/admin/training-data/bulk-approve": {}
  "/api/admin/training-data/export": {}
  "/api/admin/users": {}
  "/api/admin/users/[id]": { "id": string; }
  "/api/admin/verify": {}
  "/api/admin/vocabulary": {}
  "/api/admin/vocabulary/[id]": { "id": string; }
  "/api/admin/vocabulary/export": {}
  "/api/admin/vocabulary/seed": {}
  "/api/analyze-contract": {}
  "/api/analyze-rights": {}
  "/api/analyze-unified": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/chat": {}
  "/api/credit-check": {}
  "/api/cron/fraud-import": {}
  "/api/cron/registry-monitor": {}
  "/api/extract-pdf": {}
  "/api/feasibility/parse": {}
  "/api/feasibility/report": {}
  "/api/feasibility/verify": {}
  "/api/fraud-cases": {}
  "/api/fraud-risk": {}
  "/api/generate-document": {}
  "/api/monitoring": {}
  "/api/monitoring/alerts": {}
  "/api/monitoring/alerts/[id]": { "id": string; }
  "/api/parse-registry": {}
  "/api/predict-value": {}
  "/api/predict-value/compare": {}
  "/api/real-price": {}
  "/api/scholar/search": {}
  "/api/stt/transcribe": {}
  "/api/subscription": {}
  "/api/subscription/cancel": {}
  "/api/user/migrate-data": {}
  "/api/user/notifications": {}
  "/api/user/profile": {}
  "/api/user/setup-role": {}
  "/api/user/usage": {}
  "/api/verification/request": {}
  "/api/verification/respond": {}
  "/api/verification/shared": {}
  "/api/verification/shared/[id]": { "id": string; }
  "/assistant": {}
  "/contract": {}
  "/dashboard": {}
  "/feasibility": {}
  "/jeonse": {}
  "/jeonse/analysis": {}
  "/jeonse/fixed-date": {}
  "/jeonse/jeonse-right": {}
  "/jeonse/lease-registration": {}
  "/jeonse/lease-report": {}
  "/jeonse/transfer": {}
  "/legal": {}
  "/login": {}
  "/prediction": {}
  "/pricing": {}
  "/privacy": {}
  "/profile": {}
  "/registry": {}
  "/report": {}
  "/rights": {}
  "/signup": {}
  "/tax": {}
  "/terms": {}
  "/verification": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/jeonse": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
