// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(app)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/(app)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/api-hub/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-hub">> = Specific
  const handler = {} as typeof import("../../../app/(app)/api-hub/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assistant">> = Specific
  const handler = {} as typeof import("../../../app/(app)/assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/contract/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contract">> = Specific
  const handler = {} as typeof import("../../../app/(app)/contract/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/feasibility/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feasibility">> = Specific
  const handler = {} as typeof import("../../../app/(app)/feasibility/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/jeonse/analysis/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jeonse/analysis">> = Specific
  const handler = {} as typeof import("../../../app/(app)/jeonse/analysis/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/jeonse/fixed-date/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jeonse/fixed-date">> = Specific
  const handler = {} as typeof import("../../../app/(app)/jeonse/fixed-date/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/jeonse/jeonse-right/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jeonse/jeonse-right">> = Specific
  const handler = {} as typeof import("../../../app/(app)/jeonse/jeonse-right/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/jeonse/lease-registration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jeonse/lease-registration">> = Specific
  const handler = {} as typeof import("../../../app/(app)/jeonse/lease-registration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/jeonse/lease-report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jeonse/lease-report">> = Specific
  const handler = {} as typeof import("../../../app/(app)/jeonse/lease-report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/jeonse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jeonse">> = Specific
  const handler = {} as typeof import("../../../app/(app)/jeonse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/jeonse/transfer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jeonse/transfer">> = Specific
  const handler = {} as typeof import("../../../app/(app)/jeonse/transfer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(app)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/prediction/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/prediction">> = Specific
  const handler = {} as typeof import("../../../app/(app)/prediction/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../app/(app)/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/registry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/registry">> = Specific
  const handler = {} as typeof import("../../../app/(app)/registry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/report/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/report">> = Specific
  const handler = {} as typeof import("../../../app/(app)/report/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/rights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rights">> = Specific
  const handler = {} as typeof import("../../../app/(app)/rights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/signup">> = Specific
  const handler = {} as typeof import("../../../app/(app)/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/tax/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tax">> = Specific
  const handler = {} as typeof import("../../../app/(app)/tax/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/verification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verification">> = Specific
  const handler = {} as typeof import("../../../app/(app)/verification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(landing)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(landing)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(landing)/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../app/(landing)/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/legal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal">> = Specific
  const handler = {} as typeof import("../../../app/legal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/account">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/analyses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/analyses">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/analyses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/announcements/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/announcements/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/announcements/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/announcements">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/audit-logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/audit-logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/training-data/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/training-data/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/training-data/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/training-data/bulk-approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/training-data/bulk-approve">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/training-data/bulk-approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/training-data/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/training-data/export">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/training-data/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/training-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/training-data">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/training-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/vocabulary/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vocabulary/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/vocabulary/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/vocabulary/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vocabulary/export">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/vocabulary/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/vocabulary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vocabulary">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/vocabulary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/admin/vocabulary/seed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/vocabulary/seed">> = Specific
  const handler = {} as typeof import("../../../app/api/admin/vocabulary/seed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analyze-contract/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze-contract">> = Specific
  const handler = {} as typeof import("../../../app/api/analyze-contract/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analyze-rights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze-rights">> = Specific
  const handler = {} as typeof import("../../../app/api/analyze-rights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analyze-unified/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze-unified">> = Specific
  const handler = {} as typeof import("../../../app/api/analyze-unified/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/credit-check/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/credit-check">> = Specific
  const handler = {} as typeof import("../../../app/api/credit-check/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/fraud-import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/fraud-import">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/fraud-import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cron/registry-monitor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/registry-monitor">> = Specific
  const handler = {} as typeof import("../../../app/api/cron/registry-monitor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/extract-pdf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/extract-pdf">> = Specific
  const handler = {} as typeof import("../../../app/api/extract-pdf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/feasibility/parse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feasibility/parse">> = Specific
  const handler = {} as typeof import("../../../app/api/feasibility/parse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/feasibility/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feasibility/report">> = Specific
  const handler = {} as typeof import("../../../app/api/feasibility/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/feasibility/verify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feasibility/verify">> = Specific
  const handler = {} as typeof import("../../../app/api/feasibility/verify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/fraud-cases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fraud-cases">> = Specific
  const handler = {} as typeof import("../../../app/api/fraud-cases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/fraud-risk/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/fraud-risk">> = Specific
  const handler = {} as typeof import("../../../app/api/fraud-risk/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/generate-document/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-document">> = Specific
  const handler = {} as typeof import("../../../app/api/generate-document/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/monitoring/alerts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/alerts/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/monitoring/alerts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/monitoring/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring/alerts">> = Specific
  const handler = {} as typeof import("../../../app/api/monitoring/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/monitoring/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring">> = Specific
  const handler = {} as typeof import("../../../app/api/monitoring/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/parse-registry/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parse-registry">> = Specific
  const handler = {} as typeof import("../../../app/api/parse-registry/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/predict-value/compare/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/predict-value/compare">> = Specific
  const handler = {} as typeof import("../../../app/api/predict-value/compare/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/predict-value/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/predict-value">> = Specific
  const handler = {} as typeof import("../../../app/api/predict-value/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/real-price/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/real-price">> = Specific
  const handler = {} as typeof import("../../../app/api/real-price/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/scholar/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scholar/search">> = Specific
  const handler = {} as typeof import("../../../app/api/scholar/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stt/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stt/transcribe">> = Specific
  const handler = {} as typeof import("../../../app/api/stt/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/subscription/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription/cancel">> = Specific
  const handler = {} as typeof import("../../../app/api/subscription/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/subscription/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscription">> = Specific
  const handler = {} as typeof import("../../../app/api/subscription/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/migrate-data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/migrate-data">> = Specific
  const handler = {} as typeof import("../../../app/api/user/migrate-data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/notifications">> = Specific
  const handler = {} as typeof import("../../../app/api/user/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/profile">> = Specific
  const handler = {} as typeof import("../../../app/api/user/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/setup-role/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/setup-role">> = Specific
  const handler = {} as typeof import("../../../app/api/user/setup-role/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/user/usage/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/user/usage">> = Specific
  const handler = {} as typeof import("../../../app/api/user/usage/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/verification/request/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verification/request">> = Specific
  const handler = {} as typeof import("../../../app/api/verification/request/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/verification/respond/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verification/respond">> = Specific
  const handler = {} as typeof import("../../../app/api/verification/respond/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/verification/shared/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verification/shared/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/verification/shared/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/verification/shared/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/verification/shared">> = Specific
  const handler = {} as typeof import("../../../app/api/verification/shared/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/(app)/jeonse/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/jeonse">> = Specific
  const handler = {} as typeof import("../../../app/(app)/jeonse/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(landing)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/(landing)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
