import type { ListingItem } from "@/app/(app)/listings/hooks/useListings";

/**
 * 테스트 전용 강남 샘플 매물 (3건, 1건 안심인증)
 *
 * ⚠️ 운영(vestra-plum) 도메인에서는 절대 렌더링하지 않는다. (ListingsListClient의 showFixtures 게이팅)
 * DB에 쓰지 않는 UI 픽스처이며, 실데이터(매물)가 비어있을 때 테스트 화면 확인용으로만 노출한다.
 */
export const GANGNAM_TEST_LISTINGS: ListingItem[] = [
  {
    id: "test-gangnam-1",
    listingType: "SALE",
    address: "서울시 강남구 대치동 966 대치아이파크",
    roomType: "아파트",
    size: 84,
    floor: 12,
    totalFloor: 25,
    deposit: "1350000000",
    managementFee: null,
    duration: null,
    availableFrom: null,
    photos: null,
    description: "테스트 샘플 매물 (안심인증)",
    safetyDocuments: null,
    officialPrice: null,
    jeonseRatio: null,
    isCertified: true,
    certifiedAt: "2026-08-01T00:00:00.000Z",
    taxDocUrl: null,
    taxDocFilename: null,
    buildingDocUrl: null,
    insuranceResult: null,
    status: "ACTIVE",
    viewCount: 128,
    analysisId: null,
    latitude: 37.49500191860841,
    longitude: 127.0545643652613,
    createdAt: "2026-08-01T00:00:00.000Z",
    owner: { id: "test-owner-1", name: "테스트 임대사업자", role: "RENTAL_BIZ", companyName: "베스트라 테스트" },
    _count: { applications: 0 },
  },
  {
    id: "test-gangnam-2",
    listingType: "JEONSE",
    address: "서울시 강남구 역삼동 736 역삼래미안",
    roomType: "아파트",
    size: 59,
    floor: 8,
    totalFloor: 20,
    deposit: "620000000",
    managementFee: null,
    duration: 24,
    availableFrom: null,
    photos: null,
    description: "테스트 샘플 매물",
    safetyDocuments: null,
    officialPrice: null,
    jeonseRatio: null,
    isCertified: false,
    certifiedAt: null,
    taxDocUrl: null,
    taxDocFilename: null,
    buildingDocUrl: null,
    insuranceResult: null,
    status: "ACTIVE",
    viewCount: 64,
    analysisId: null,
    latitude: 37.49751592497375,
    longitude: 127.05004728330309,
    createdAt: "2026-08-02T00:00:00.000Z",
    owner: { id: "test-owner-2", name: "테스트 중개사", role: "REALESTATE", companyName: "강남부동산" },
    _count: { applications: 0 },
  },
  {
    id: "test-gangnam-3",
    listingType: "SALE",
    address: "서울시 강남구 삼성동 159 삼성힐스테이트",
    roomType: "오피스텔",
    size: 45,
    floor: 15,
    totalFloor: 30,
    deposit: "480000000",
    managementFee: null,
    duration: null,
    availableFrom: null,
    photos: null,
    description: "테스트 샘플 매물",
    safetyDocuments: null,
    officialPrice: null,
    jeonseRatio: null,
    isCertified: false,
    certifiedAt: null,
    taxDocUrl: null,
    taxDocFilename: null,
    buildingDocUrl: null,
    insuranceResult: null,
    status: "ACTIVE",
    viewCount: 41,
    analysisId: null,
    latitude: 37.516307951190136,
    longitude: 127.04844908379533,
    createdAt: "2026-08-03T00:00:00.000Z",
    owner: { id: "test-owner-3", name: "홍길동", role: "PERSONAL", companyName: null },
    _count: { applications: 0 },
  },
];
