// 기업 정보 및 상수 데이터 — 수정 시 이 파일만 변경하면 전체 반영

module.exports = {
  company: {
    name: "(주)비엠아이씨엔에스",
    nameEn: "BMI C&S Co., Ltd.",
    ceo: "김동의",
    bizNo: "263-87-03481",
    comSalesNo: "2025-경기광명-0189",
    address: "서울시 강남구 강남대로 354(역삼동, 혜천빌딩) 1126-5호",
    industry: "소프트웨어 개발업 (정보통신업)",
    bizType: "AI / 프롭테크",
    founded: "2024년",
    employees: "1명 (대표 겸 CTO)",
    phone: "010-8490-9271",
    email: "",
    patent: {
      name: "부동산 거래 위험도 산출장치 및 방법",
      number: "10-2026-0085160",
    },
  },
  product: {
    name: "VESTRA",
    fullName: "AI 기반 부동산 풀체인 분석 플랫폼",
    meaning: "Verified Estate Safety through Trusted Real-time AI",
    version: "v5.13.4",
    loc: "31,315+",
    engines: "8종",
    engineLoc: "5,111",
    apis: "49개",
    dbModels: "25개",
    modules: "11개",
    pages: "26개",
    components: "37개",
    url: "https://vestra-plum.vercel.app",
    devPeriod: "2026년 2월 ~ 현재 (약 3개월)",
  },
  finance: {
    fundingAmount: "1억 원",
    year1Revenue: "7.7억 원",
    year2Revenue: "39.6억 원",
    year3Revenue: "120억 원",
    cumulativeRevenue: "167.3억 원",
    roi: "16,630%",
    bep: "1차년도",
  },
  market: {
    tam: "약 6,000조 원",
    tamDesc: "국내 부동산 자산 총액",
    sam: "연 600억 원",
    samDesc: "공인중개사 51만 명 + 자산관리 3,000개사 대상 SaaS",
    som: "연 7.7억 원",
    somDesc: "1차년도 B2B 500명 전환 (전환율 0.1%)",
  },
  partners: [
    { name: "등기온 (dgon)", role: "법률 실행", asset: "법무법인 시화 네트워크, 온라인 등기", status: "협의 중" },
    { name: "제온스 (ezREMS)", role: "데이터·관리", asset: "20년 실거래 DB, 51,000+ 세대 관리", status: "협의 중" },
    { name: "MJIT", role: "AI 고도화", asset: "LLM 구축 전문", status: "협의 중" },
    { name: "법무법인 시화", role: "법률 자문", asset: "부동산 법무 전문", status: "확정" },
  ],
  documentDate: "2026년 5월",
};
