var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/training-data/route.js")
R.c("server/chunks/node_modules_unpdf_dist_pdfjs_mjs_8abb7088._.js")
R.c("server/chunks/node_modules_next_fb9ef344._.js")
R.c("server/chunks/97170_@auth_core_b390930a._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_868b124b._.js")
R.c("server/chunks/[root-of-the-server]__4c0d3392._.js")
R.c("server/chunks/[root-of-the-server]__db62078e._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_training-data_route_actions_b62c66dc.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/admin/training-data/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/admin/training-data/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
