var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/analyze-unified/route.js")
R.c("server/chunks/[root-of-the-server]__9da8b173._.js")
R.c("server/chunks/node_modules_next_9d7d1160._.js")
R.c("server/chunks/node_modules_openai_83494e57._.js")
R.c("server/chunks/97170_@auth_core_b390930a._.js")
R.c("server/chunks/node_modules_jose_dist_webapi_868b124b._.js")
R.c("server/chunks/[root-of-the-server]__ffc7ca1f._.js")
R.c("server/chunks/_next-internal_server_app_api_analyze-unified_route_actions_924a94f0.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/analyze-unified/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/app/api/analyze-unified/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
